<script setup lang="ts">

</script>

<template>
    <template v-if="$route.name === 'bookings'">
        <div> Bookings 1 </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings </div>
        <div> Bookings  last</div>
    </template>
    <NuxtPage v-else />
</template>

<style scoped lang="scss">

</style>
